<?php
$brand=is_array($brand??null)?$brand:[];
$hasLogo=trim((string)($brand['logo_path']??setting('logo_path','')))!=='';
$hasFavicon=trim((string)($brand['favicon_path']??setting('favicon_path','')))!=='';
$hasLoginBackground=trim((string)($brand['login_background_path']??setting('login_background_path','')))!=='';
?>
<div class="page-head"><div><h1>Внешний вид и брендинг</h1><p>Название, логотип и оформление используются на входе, в Studio и на всех публичных страницах.</p></div><a class="button" target="_blank" rel="noopener" href="<?=e(app_url('/'))?>">Открыть сайт</a></div>
<form method="post" enctype="multipart/form-data" action="<?=e(app_url('/studio/appearance'))?>">
<?=csrf_field()?>
<section class="panel branding-panel">
 <div class="panel-title-row"><div><h2>Бренд сайта</h2><p>Загрузите один логотип — система покажет его в шапке сайта, на странице входа, регистрации, в личном кабинете и в KOVCHEG Studio.</p></div></div>
 <div class="branding-grid">
  <div class="branding-preview-card"><span>Текущий логотип</span><div class="branding-logo-preview"><img src="<?=e(app_url('/brand/logo?v='.rawurlencode(ASSET_REVISION)))?>" alt="Логотип"></div><label class="button small">Загрузить логотип<input hidden type="file" name="brand_logo" accept="image/jpeg,image/png,image/webp"></label><?php if($hasLogo):?><label class="check-row"><input type="checkbox" name="remove_logo" value="1"> Удалить логотип</label><?php endif;?><small>JPG, PNG или WebP до 12 МБ. Лучше прозрачный PNG/WebP.</small></div>
  <div class="branding-preview-card"><span>Иконка сайта</span><div class="branding-favicon-preview"><img src="<?=e($hasFavicon?app_url('/brand/favicon?v='.rawurlencode(ASSET_REVISION)):app_url('/assets/icons/icon.svg?v='.rawurlencode(ASSET_REVISION)))?>" alt="Favicon"></div><label class="button small">Загрузить favicon<input hidden type="file" name="brand_favicon" accept="image/jpeg,image/png,image/webp"></label><?php if($hasFavicon):?><label class="check-row"><input type="checkbox" name="remove_favicon" value="1"> Удалить favicon</label><?php endif;?><small>Квадратное изображение, рекомендуется 512×512.</small></div>
  <div class="branding-preview-card branding-preview-card--wide"><span>Фон страницы входа</span><div class="branding-login-preview" <?=$hasLoginBackground?'style="background-image:url(\''.e(app_url('/brand/login-background?v='.rawurlencode(ASSET_REVISION))).'\')"':''?>><img src="<?=e(app_url('/brand/logo?v='.rawurlencode(ASSET_REVISION)))?>" alt=""><b><?=e(setting('site_name','KOVCHEG CMS'))?></b></div><label class="button small">Загрузить фон входа<input hidden type="file" name="login_background" accept="image/jpeg,image/png,image/webp"></label><?php if($hasLoginBackground):?><label class="check-row"><input type="checkbox" name="remove_login_background" value="1"> Удалить фон</label><?php endif;?><small>Необязательно. Без файла используется спокойный системный фон.</small></div>
 </div>
 <div class="settings-columns branding-fields"><section><div class="field"><label>Название сайта</label><input name="site_name" maxlength="150" required value="<?=e(setting('site_name','KOVCHEG CMS'))?>"></div><div class="field"><label>Подзаголовок</label><input name="blog_tagline" maxlength="300" value="<?=e(setting('blog_tagline',''))?>"></div></section><section><div class="field"><label>Основной цвет бренда</label><input type="color" name="brand_accent" value="<?=e((string)($brand['accent']??setting('brand_accent','#2563eb')))?>"></div><div class="field"><label>Заголовок на странице входа</label><input name="login_heading" maxlength="220" value="<?=e(setting('login_heading','Всё управление сайтом — в одном месте.'))?>"></div></section></div>
</section>

<section class="panel" style="margin-top:18px"><h2>Тема сайта</h2><div class="theme-grid"><?php foreach($themes as $theme):?><label class="theme-card <?=$theme['active']?'active':''?>"><div class="theme-preview"><?php if($theme['preview']!==''):?><img src="<?=e(app_url('/themes/'.$theme['slug'].'/'.$theme['preview']))?>" alt="" style="width:100%;height:100%;object-fit:cover"><?php else:?>KOVCHEG THEME<?php endif;?></div><div class="theme-card__body"><div class="check-row"><input type="radio" name="blog_theme" value="<?=e($theme['slug'])?>" <?=$theme['active']?'checked':''?>><h3><?=e($theme['name'])?></h3></div><p><?=e($theme['description'])?></p><small>Версия <?=e($theme['version'])?> · <?=e($theme['author'])?></small></div></label><?php endforeach;?></div></section>

<div class="settings-columns" style="margin-top:18px"><section class="panel"><h2>Описание сайта</h2><div class="field"><label>Краткое описание</label><textarea name="blog_description" rows="5" maxlength="1000"><?=e(setting('blog_description','Информация и материалы сайта.'))?></textarea></div></section><section class="panel"><h2>Подвал</h2><div class="field"><label>Текст в подвале</label><textarea name="blog_footer_text" rows="5" maxlength="1000"><?=e(setting('blog_footer_text','Сайт работает на KOVCHEG CMS.'))?></textarea></div></section></div>
<div style="margin-top:18px"><button class="button primary">Сохранить брендинг и оформление</button></div>
</form>
