<?php
$typeLabels=['post'=>'Публикация','page'=>'Страница','portfolio'=>'Работа портфолио'];
$isNew=empty($entry['id']);
$publishedLocal='';if(!empty($entry['published_at']))$publishedLocal=date('Y-m-d\TH:i',strtotime((string)$entry['published_at']));
$meta=is_array($entry['meta']??null)?$entry['meta']:[];
?>
<form method="post" enctype="multipart/form-data" action="<?=e(app_url('/studio/content/save'))?>" data-entry-form>
<?=csrf_field()?><input type="hidden" name="id" value="<?=(int)($entry['id']??0)?>"><input type="hidden" name="content_json" value="<?=e((string)($entry['content_json']??'[]'))?>" data-block-json>
<div class="page-head"><div><h1><?=$isNew?'Новый материал':'Редактирование материала'?></h1><p><?=e($typeLabels[$entry['type']]??'Материал')?> · <?=$isNew?'ещё не сохранён':'ID '.(int)$entry['id']?></p></div><div class="editor-actions"><a class="button" href="<?=e(app_url('/studio/content'))?>">К списку</a><?php if(!$isNew&&$entry['status']==='published'):?><a class="button" target="_blank" href="<?=e(\Kovcheg\Blog\Blog::entryUrl($entry))?>">Открыть на сайте</a><?php endif;?><button class="button primary" type="submit">Сохранить</button></div></div>
<div class="editor-layout">
 <div class="editor-main">
  <section class="editor-card"><div class="field"><label>Заголовок</label><input class="title-input" data-entry-title name="title" maxlength="255" required value="<?=e((string)$entry['title'])?>" placeholder="Название публикации"></div><div class="form-grid"><div class="field"><label>Адрес</label><input data-entry-slug name="slug" maxlength="190" value="<?=e((string)$entry['slug'])?>" placeholder="adres-materiala"></div><div class="field"><label>Тип</label><select name="type"><?php foreach($typeLabels as $key=>$label):?><option value="<?=e($key)?>" <?=$entry['type']===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></div></div><div class="field"><label>Краткое описание</label><textarea name="excerpt" rows="4" maxlength="2000" placeholder="Анонс для карточки и поисковых систем"><?=e((string)($entry['excerpt']??''))?></textarea></div></section>
  <section class="editor-card"><h2>Содержание</h2><div class="block-toolbar" data-block-toolbar><?php foreach(['paragraph'=>'Текст','heading'=>'Заголовок','image'=>'Фото','quote'=>'Цитата','list'=>'Список','columns'=>'Колонки','button'=>'Кнопка','video'=>'Видео','code'=>'Код','separator'=>'Линия'] as $key=>$label):?><button type="button" data-add-block="<?=e($key)?>">+ <?=e($label)?></button><?php endforeach;?></div><div class="block-editor" data-block-editor></div></section>
  <?php if($entry['type']==='portfolio'):?><section class="editor-card"><h2>Карточка проекта</h2><div class="form-grid"><div class="field"><label>Заказчик или проект</label><input name="portfolio_client" value="<?=e((string)($meta['client']??''))?>"></div><div class="field"><label>Год</label><input name="portfolio_year" maxlength="20" value="<?=e((string)($meta['year']??''))?>"></div><div class="field"><label>Роль / специализация</label><input name="portfolio_role" value="<?=e((string)($meta['role']??''))?>"></div><div class="field"><label>Ссылка на проект</label><input name="portfolio_url" value="<?=e((string)($meta['project_url']??''))?>" placeholder="https://"></div></div></section><?php endif;?>
  <section class="editor-card"><h2>SEO</h2><div class="field"><label>SEO-заголовок</label><input name="seo_title" maxlength="255" value="<?=e((string)($entry['seo_title']??''))?>"><small>Оставьте пустым, чтобы использовать основной заголовок.</small></div><div class="field"><label>Описание для поиска и соцсетей</label><textarea name="seo_description" rows="3" maxlength="320"><?=e((string)($entry['seo_description']??''))?></textarea></div></section>
  <?php if($revisions):?><section class="editor-card"><h2>История изменений</h2><div class="simple-list"><?php foreach($revisions as $revision):?><article><div><b><?=e($revision['title'])?></b><small><?=e($revision['author_name'])?> · <?=e($revision['created_at'])?></small></div><form method="post" data-confirm="Восстановить эту версию? Текущая версия сохранится в истории." action="<?=e(app_url('/studio/revisions/'.(int)$revision['id'].'/restore'))?>"><?=csrf_field()?><button class="button small">Восстановить</button></form></article><?php endforeach;?></div></section><?php endif;?>
 </div>
 <aside class="editor-side">
  <section class="editor-card"><h3>Публикация</h3><div class="field"><label>Статус</label><select name="status"><option value="draft" <?=$entry['status']==='draft'?'selected':''?>>Черновик</option><option value="published" <?=$entry['status']==='published'?'selected':''?>>Опубликовано</option><option value="scheduled" <?=$entry['status']==='scheduled'?'selected':''?>>Запланировано</option><option value="private" <?=$entry['status']==='private'?'selected':''?>>Приватно</option></select></div><div class="field"><label>Дата публикации</label><input type="datetime-local" name="published_at" value="<?=e($publishedLocal)?>"></div><div class="field"><label>Видимость</label><select name="visibility"><option value="public" <?=$entry['visibility']==='public'?'selected':''?>>Всем</option><option value="users" <?=$entry['visibility']==='users'?'selected':''?>>Только пользователям</option><option value="private" <?=$entry['visibility']==='private'?'selected':''?>>Только администрации</option></select></div><label class="check-row"><input type="checkbox" name="is_featured" value="1" <?=!empty($entry['is_featured'])?'checked':''?>> Закрепить / выделить</label><label class="check-row"><input type="checkbox" name="comments_enabled" value="1" <?=!empty($entry['comments_enabled'])?'checked':''?>> Разрешить комментарии</label><label class="check-row"><input type="checkbox" name="reactions_enabled" value="1" <?=!empty($entry['reactions_enabled'])?'checked':''?>> Разрешить реакции</label><div class="field"><label>Порядок</label><input type="number" name="sort_order" value="<?=(int)($entry['sort_order']??0)?>"></div><button class="button primary" type="submit">Сохранить материал</button></section>
  <section class="editor-card"><h3>Обложка</h3><input type="hidden" name="featured_image_path" data-feature-path value="<?=e((string)($entry['featured_image_path']??''))?>"><div class="field"><label>Загрузить новую</label><input type="file" name="featured_image" accept="image/jpeg,image/png,image/webp"></div><?php if($media):?><div class="media-picker"><?php foreach($media as $item):?><button type="button" class="<?=$entry['featured_image_path']===$item['stored_path']?'active':''?>" data-media-path="<?=e($item['stored_path'])?>" title="<?=e($item['title']??$item['original_name'])?>"><img src="<?=e(app_url('/media/'.(int)$item['id']))?>" alt=""></button><?php endforeach;?></div><?php else:?><small>В медиатеке пока нет изображений.</small><?php endif;?></section>
  <section class="editor-card"><h3>Рубрики</h3><div class="check-list"><?php foreach($categories as $category):?><label class="check-row"><input type="checkbox" name="category_ids[]" value="<?=(int)$category['id']?>" <?=in_array((int)$category['id'],array_map('intval',(array)$entry['category_ids']),true)?'checked':''?>> <?=e($category['name'])?></label><?php endforeach;?></div><a class="button small" href="<?=e(app_url('/studio/categories'))?>">Управление рубриками</a></section>
  <section class="editor-card"><h3>Теги</h3><div class="field"><input name="tags" value="<?=e((string)($entry['tags_text']??''))?>" placeholder="разработка, новости, KOVCHEG"><small>Разделяйте запятыми.</small></div></section>
  <section class="editor-card"><h3>Шаблон</h3><div class="field"><input name="template" maxlength="80" value="<?=e((string)($entry['template']??''))?>" placeholder="default"></div></section>
 </aside>
</div>
</form>
