<div class="page-head"><div><h1>Медиатека</h1><p>Изображения, документы, музыка и видео, разложенные по папкам.</p></div><form method="get" action="<?=e(app_url('/studio/media'))?>"><input type="hidden" name="folder" value="<?=(int)$folder?>"><input name="q" value="<?=e($search)?>" placeholder="Поиск по названию"><button class="button">Найти</button></form></div>
<div class="folder-layout">
 <aside class="folder-sidebar">
  <section class="panel"><h3>Папки</h3><nav class="folder-list"><a class="<?=$folder===0?'active':''?>" href="<?=e(app_url('/studio/media'))?>"><span>Все файлы</span><b><?=count($media)?></b></a><?php foreach($folders as $item):?><a class="<?=$folder===(int)$item['id']?'active':''?>" href="<?=e(app_url('/studio/media?folder='.(int)$item['id']))?>"><span><?=e((string)$item['name'])?></span><b><?=(int)$item['media_count']?></b></a><?php endforeach;?></nav><hr><form method="post" action="<?=e(app_url('/studio/media/folders'))?>"><?=csrf_field()?><div class="field"><label>Новая папка</label><input name="name" maxlength="150" required placeholder="Например, Обложки"></div><button class="button small">Создать папку</button></form></section>
 </aside>
 <div>
  <section class="panel" style="margin-bottom:18px"><h2>Загрузить файлы</h2><form method="post" enctype="multipart/form-data" action="<?=e(app_url('/studio/media/upload'))?>"><?=csrf_field()?><div class="form-grid"><div class="field"><label>Папка</label><select name="folder_id"><option value="0">Без папки</option><?php foreach($folders as $item):?><option value="<?=(int)$item['id']?>" <?=$folder===(int)$item['id']?'selected':''?>><?=e((string)$item['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Файлы</label><input type="file" name="media[]" multiple accept="image/jpeg,image/png,image/webp,application/pdf,audio/mpeg,audio/ogg,video/mp4,video/webm,application/zip"><small>До 30 файлов за раз, каждый не больше 40 МБ.</small></div></div><button class="button primary">Загрузить в медиатеку</button></form></section>
  <?php if($media):?><div class="media-grid"><?php foreach($media as $item):?><article class="media-card"><div class="media-card__preview"><?php if(str_starts_with((string)$item['mime_type'],'image/')):?><img src="<?=e(app_url('/media/'.(int)$item['id']))?>" alt="<?=e($item['alt_text']??'')?>" loading="lazy"><?php else:?><strong><?=e(strtoupper(pathinfo((string)$item['original_name'],PATHINFO_EXTENSION)?:'FILE'))?></strong><?php endif;?></div><div class="media-card__body"><b><?=e($item['title']??$item['original_name'])?></b><small><?=e($item['mime_type'])?> · <?=e(format_bytes((int)$item['file_size']))?></small><small><?=e((string)($item['folder_name']??'Без папки'))?> · <?=e($item['uploader_name'])?></small><div class="table-actions" style="margin-top:9px"><a class="button small" target="_blank" href="<?=e(app_url('/media/'.(int)$item['id']))?>">Открыть</a><form method="post" data-confirm="Удалить этот файл из медиатеки?" action="<?=e(app_url('/studio/media/'.(int)$item['id'].'/delete'))?>"><?=csrf_field()?><button class="button small danger">Удалить</button></form></div><details><summary>Описание и папка</summary><form class="media-edit-form" method="post" action="<?=e(app_url('/studio/media/'.(int)$item['id'].'/update'))?>"><?=csrf_field()?><input name="title" value="<?=e((string)($item['title']??''))?>" placeholder="Название"><input name="alt_text" value="<?=e((string)($item['alt_text']??''))?>" placeholder="Описание изображения"><textarea name="caption" rows="2" placeholder="Подпись"><?=e((string)($item['caption']??''))?></textarea><select name="folder_id"><option value="0">Без папки</option><?php foreach($folders as $folderItem):?><option value="<?=(int)$folderItem['id']?>" <?=(int)($item['folder_id']??0)===(int)$folderItem['id']?'selected':''?>><?=e((string)$folderItem['name'])?></option><?php endforeach;?></select><button class="button small">Сохранить</button></form></details></div></article><?php endforeach;?></div><?php else:?><div class="empty-state">В этой папке файлов пока нет.</div><?php endif;?>
 </div>
</div>
