<?php $currentUser=\Kovcheg\Auth::user()??[];$permissions=user_permissions();?>
<main class="channel-post-page channel-post-page-200" data-channel-post-page data-channel-id="<?=(int)$chat['id']?>" data-root-id="<?=(int)$root['id']?>">
 <?=\Kovcheg\View::partial('site-sidebar',['active'=>'messages'])?>
 <section class="channel-post-center">
  <header class="channel-post-page-head channel-post-fixed-head"><a href="<?=e(chat_public_url($chat))?>">‹ Назад в канал</a><div><?=chat_avatar_html($chat,null,'avatar-sm')?><span><b><?=e($chat['title']??'Канал')?></b><small>Публикация и обсуждение</small></span></div></header>
  <div class="channel-post-scroll" data-channel-post-scroll>
   <div class="channel-post-thread">
    <article class="channel-post-root"><?=\Kovcheg\View::partial('message',['m'=>$root,'postViewerMode'=>true])?></article>
    <section class="channel-post-comments"><header><h2>Комментарии</h2><span data-channel-comment-count><?=count($comments)?></span></header><div class="channel-post-comments-list" data-channel-post-comments-list><?php foreach(($commentTree??[]) as $comment)echo \Kovcheg\View::partial('channel-comment',['comment'=>$comment,'rootId'=>(int)$root['id']]);?><?php if(!$comments):?><p class="empty-thread" data-channel-comments-empty>Комментариев пока нет.</p><?php endif;?></div></section>
   </div>
  </div>
  <?php if(!empty($chat['comments_enabled'])):?><form id="channel-comment-composer" class="channel-comment-composer channel-comment-composer-fixed" data-channel-comment-form enctype="multipart/form-data"><input type="hidden" name="chat_id" value="<?=(int)$chat['id']?>"><input type="hidden" name="root_id" value="<?=(int)$root['id']?>"><input type="hidden" name="parent_id" value="<?=(int)$root['id']?>"><div class="channel-comment-reply-context" data-channel-comment-reply-context hidden>Ответ <b></b><button type="button" data-channel-comment-reply-cancel>×</button></div><?=avatar_html($currentUser,'avatar-xs')?><button type="button" class="icon-btn" data-channel-emoji title="Смайлики">☺</button><?php if(!empty($permissions['can_send_voice'])):?><button type="button" class="icon-btn" data-channel-voice title="Голосовое">🎙</button><?php endif;?><?php if(!empty($permissions['can_send_files'])):?><label class="icon-btn file-pick" title="Прикрепить">📎<input type="file" name="files[]" multiple hidden data-channel-comment-files></label><?php endif;?><div class="channel-comment-input"><textarea name="body" rows="1" maxlength="5000" placeholder="Написать комментарий"></textarea><div class="channel-voice-state" data-channel-voice-state hidden><i></i><b data-channel-voice-time>0:00</b><span>Идёт запись</span><button type="button" data-channel-voice-cancel>×</button></div></div><button class="send-btn" type="submit">➤</button><div class="channel-emoji-picker" data-channel-emoji-picker hidden></div><div class="channel-comment-files" data-channel-comment-file-list></div></form><?php else:?><p class="read-only-composer channel-comment-composer-fixed">Комментарии отключены владельцем канала.</p><?php endif;?>
 </section>
</main>
<div class="comment-context-menu" data-channel-comment-menu hidden><button type="button" data-channel-comment-action="reply">Ответить</button><button type="button" data-channel-comment-action="copy">Скопировать текст</button><button type="button" data-channel-comment-action="edit">Редактировать</button><button type="button" class="danger" data-channel-comment-action="delete">Удалить</button></div>
