<?php
$attachments=$post['attachments']??[];$images=array_values(array_filter($attachments,fn($a)=>str_starts_with((string)($a['mime_type']??''),'image/')));$videos=array_values(array_filter($attachments,fn($a)=>str_starts_with((string)($a['mime_type']??''),'video/')));$documents=array_values(array_filter($attachments,fn($a)=>!str_starts_with((string)($a['mime_type']??''),'image/')&&!str_starts_with((string)($a['mime_type']??''),'video/')));$comments=$post['comments']??[];$postReactions=$post['reactions']??[];$myPostReaction=$post['my_reaction']??null;$reactionTotal=(int)($post['reaction_total']??array_sum(array_map(fn($x)=>(int)($x['count']??0),$postReactions)));
$author=['id'=>$post['author_id'],'display_name'=>$post['author_name'],'username'=>$post['author_username'],'avatar_path'=>$post['avatar_path']??null,'is_verified'=>$post['is_verified']??0,'verification_label'=>$post['verification_label']??null];
$canDelete=(int)$post['author_id']===\Kovcheg\Auth::id()||(int)$post['user_id']===\Kovcheg\Auth::id()||\Kovcheg\Auth::isAdmin();$repost=$post['repost']??null;$repostImage=$repost?array_values(array_filter($repost['attachments']??[],fn($a)=>str_starts_with((string)($a['mime_type']??''),'image/')))[0]??null:null;$videoEmbeds=video_embeds_from_text((string)($post['body']??''));
?>
<article class="wall-post-card feed-post-090" id="wall-post-<?=(int)$post['id']?>" data-wall-post="<?=(int)$post['id']?>">
 <header class="wall-post-head"><a class="wall-author-avatar" href="<?=e(user_public_url((string)$post['author_username']))?>"><?=avatar_html($author,'avatar-md')?></a><div class="wall-author-info"><a href="<?=e(user_public_url((string)$post['author_username']))?>"><b><?=e($post['author_name'])?></b><?=verified_badge($post)?></a><?php if((int)$post['user_id']!==(int)$post['author_id']):?><small>на странице <a href="<?=e(user_public_url((string)$post['wall_username']))?>"><?=e($post['wall_name'])?></a></small><?php endif;?><time><?=e(human_time($post['created_at']))?><?php if((int)($post['author_id']??0)===\Kovcheg\Auth::id()):?><span class="wall-post-privacy" title="Видимость публикации"><?=e(match((string)($post['visibility']??'everyone')){'only_me'=>'🔒','colleagues'=>'👥','users'=>'◉',default=>'🌐'})?></span><?php endif;?></time></div><?php if(\Kovcheg\Auth::check()):?><div class="wall-post-menu-wrap"><button type="button" class="wall-more" data-wall-menu-toggle="<?=(int)$post['id']?>" aria-label="Меню публикации">•••</button><div class="wall-post-menu" data-wall-menu="<?=(int)$post['id']?>" hidden><button type="button" data-wall-repost="<?=(int)$post['id']?>">Поделиться</button><button type="button" data-wall-menu-link data-share-url="<?=e(wall_post_public_url((string)$post['wall_username'],(int)$post['id']))?>">Получить ссылку</button><?php if($canDelete):?><button type="button" class="danger" data-wall-delete="<?=(int)$post['id']?>">Удалить</button><?php endif;?></div></div><?php endif;?></header>
 <?php if($repost):?><a class="wall-repost-preview" href="<?=e(wall_post_public_url((string)$repost['wall_username'],(int)$repost['id']))?>"><header><?=avatar_html(['id'=>$repost['author_id'],'display_name'=>$repost['author_name'],'avatar_path'=>$repost['avatar_path']??null],'avatar-xs')?><span><b><?=e($repost['author_name'])?></b><small><?=e(human_time($repost['created_at']))?></small></span></header><?php if(trim((string)$repost['body'])!==''):?><p><?=e(utf8_substr(trim(strip_tags((string)$repost['body'])),0,500))?></p><?php endif;?><?php if($repostImage):?><img src="<?=e($repostImage['url'])?>" alt="Фотография репоста" loading="lazy"><?php endif;?></a><?php endif;?>
 <?php if($images):?><div class="wall-media-grid count-<?=min(4,count($images))?>"><?php foreach($images as $index=>$media):?><button class="wall-media-item" type="button" data-wall-media="<?=e($media['url'])?>" data-wall-post-id="<?=(int)$post['id']?>"><img src="<?=e($media['url'])?>" alt="Фотография записи" loading="lazy"><?php if($index===3&&count($images)>4):?><span>+<?=count($images)-4?></span><?php endif;?></button><?php if($index>=3)break;?><?php endforeach;?></div><?php endif;?>
 <?php if($videos):?><div class="wall-native-videos"><?php foreach($videos as $video):?><video controls preload="metadata" playsinline src="<?=e($video['url'])?>"></video><?php endforeach;?></div><?php endif;?>
 <?php if($documents):?><div class="wall-document-list"><?php foreach($documents as $document):?><a class="wall-document-card" href="<?=e($document['url'].'?download=1')?>"><span>📄</span><div><b><?=e($document['original_name']?:'Документ')?></b><small><?=e(format_bytes((int)$document['file_size']))?> · скачать</small></div></a><?php endforeach;?></div><?php endif;?>
 <?php if($videoEmbeds):?><div class="wall-video-embeds"><?php foreach($videoEmbeds as $embed):?><div class="wall-video-frame"><iframe src="<?=e($embed['src'])?>" title="<?=e($embed['title'])?>" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div><?php endforeach;?></div><?php endif;?>
 <?php if(trim((string)$post['body'])!==''):?><div class="wall-post-text"><?=safe_message_html((string)$post['body'])?></div><?php endif;?>
 <div class="wall-post-actions">
  <?php if(\Kovcheg\Auth::check()):?><div class="wall-reaction-wrap"><button type="button" class="wall-action wall-reaction-main <?=$myPostReaction?'active':''?>" data-wall-reaction-menu="<?=(int)$post['id']?>"><span data-wall-my-reaction><?=e($myPostReaction?:'♡')?></span><b data-wall-reaction-total><?=e($reactionTotal?:'')?></b></button><div class="wall-reaction-menu" data-wall-reaction-picker="<?=(int)$post['id']?>" hidden><?php foreach(['👍','❤️','🔥','😂','👏','😮','😢','👎'] as $emoji):?><button type="button" class="<?=$myPostReaction===$emoji?'active':''?>" data-wall-react="<?=e($emoji)?>" data-post-id="<?=(int)$post['id']?>"><?=e($emoji)?></button><?php endforeach;?></div></div><?php else:?><span class="wall-action wall-action-static"><span>♡</span><b data-wall-reaction-total><?=e($reactionTotal?:'')?></b></span><?php endif;?>
  <button type="button" class="wall-action" data-wall-comments-toggle="<?=(int)$post['id']?>"><span>💬</span><b data-wall-comment-count><?=e((int)($post['comments_count']??0)?:'')?></b></button>
  <?php if(\Kovcheg\Auth::check()):?><button type="button" class="wall-action" data-wall-repost="<?=(int)$post['id']?>"><span>↗</span><b>Репост</b></button><?php endif;?>
 </div>
 <?php if($postReactions):?><div class="wall-reaction-summary" data-wall-reaction-summary><?php foreach($postReactions as $reaction):?><?php if(\Kovcheg\Auth::check()):?><button type="button" class="<?=!empty($reaction['mine'])?'mine':''?>" data-wall-react="<?=e($reaction['emoji'])?>" data-post-id="<?=(int)$post['id']?>"><?=e($reaction['emoji'])?> <span><?=e($reaction['count'])?></span></button><?php else:?><span><?=e($reaction['emoji'])?> <span><?=e($reaction['count'])?></span></span><?php endif;?><?php endforeach;?></div><?php else:?><div class="wall-reaction-summary" data-wall-reaction-summary hidden></div><?php endif;?>
 <section class="wall-comments" data-wall-comments="<?=(int)$post['id']?>" <?=empty($comments)?'hidden':''?>><div class="wall-comments-list <?=count($comments)>3?'is-collapsed':''?>" data-wall-comments-list><?php foreach($comments as $comment)echo \Kovcheg\View::partial('profile-wall-comment',['comment'=>$comment]);?></div><?php if(count($comments)>3):?><button type="button" class="wall-comments-expand" data-wall-comments-expand>Показать все комментарии (<?=count($comments)?>)</button><?php endif;?><?php if(\Kovcheg\Auth::check()):?><form class="wall-comment-form" data-wall-comment-form action="<?=e(app_url('/profile/wall/'.(int)$post['id'].'/comment'))?>"><?=csrf_field()?><input type="hidden" name="parent_id" value=""><div class="wall-comment-reply-context" data-wall-comment-reply-context hidden>Ответ <b></b><button type="button" data-wall-comment-reply-cancel>×</button></div><div class="wall-comment-compose-row"><?=avatar_html(\Kovcheg\Auth::user()??[],'avatar-xs')?><div class="wall-comment-input-wrap"><textarea name="body" rows="1" maxlength="2000" placeholder="Написать комментарий"></textarea></div><button class="wall-comment-send" type="submit" aria-label="Отправить">➤</button></div></form><?php endif;?></section>
</article>