<?php
$isMine=(int)$m['sender_id']===\Kovcheg\Auth::id();
$threadMode=!empty($threadMode);
$postViewerMode=!empty($postViewerMode);
$showReactions=!$threadMode&&(($m['chat_type']??'direct')!=='channel'||!empty($m['reactions_enabled']));
$reactions=$showReactions?\Kovcheg\DB::all('SELECT mr.emoji,COUNT(*) count,MAX(CASE WHEN mr.user_id=? THEN 1 ELSE 0 END) mine FROM message_reactions mr WHERE mr.message_id=? GROUP BY mr.emoji ORDER BY MIN(mr.id)',[\Kovcheg\Auth::id(),(int)$m['id']]):[];
$username=(string)($m['username']??'');
$plainBody=(string)($m['body']??'');
$moderation=message_moderation_permissions((int)$m['chat_id']);
?>
<article id="m<?=(int)$m['id']?>" class="message message-type-<?=e((string)($m['type']??'text'))?> <?=$isMine?'mine':''?> <?=$threadMode?'thread-message':''?>" data-message-id="<?=(int)$m['id']?>" data-sender-id="<?=(int)$m['sender_id']?>" data-message-body="<?=e($plainBody)?>" data-message-author="<?=e($m['display_name']??'')?>" data-message-username="<?=e($username)?>" data-message-profile-url="<?=e($username!==''?user_public_url($username):'')?>" data-message-date="<?=e(!empty($m['created_at'])?date('d.m.Y H:i',strtotime((string)$m['created_at'])):'')?>" data-message-important="<?=message_is_important((int)$m['id'],\Kovcheg\Auth::id())?'1':'0'?>" data-thread-mode="<?=$threadMode?'1':'0'?>">
 <button type="button" class="message-select-control" data-message-select="<?=(int)$m['id']?>" aria-label="Выбрать сообщение"><span></span></button>
 <a class="message-avatar-link" href="<?=e($username!==''?user_public_url($username):'#')?>"><?=avatar_html($m,'avatar-sm')?></a>
 <div class="bubble">
  <header class="message-head"><a href="<?=e($username!==''?user_public_url($username):'#')?>"><strong><?=e($m['display_name']??'')?><?=verified_badge($m)?></strong><?php if($username!==''):?><small>@<?=e($username)?></small><?php endif;?></a><time><?=e(human_time($m['created_at']))?></time><span class="message-important-mark" data-message-important-mark <?=message_is_important((int)$m['id'],\Kovcheg\Auth::id())?'':'hidden'?>>★</span></header>
  <?php if(!empty($m['reply_to_id'])&&!$threadMode):?><button type="button" class="reply-quote" data-jump-message="<?=(int)$m['reply_to_id']?>"><b><?=e($m['reply_sender_name']??'Сообщение')?></b><span><?=e(utf8_substr(trim(strip_tags((string)($m['reply_body']??''))),0,120)?:'Вложение')?></span></button><?php endif;?>
  <?php if(!empty($m['forwarded_from_id'])):$fwdUser=(string)($m['forwarded_from_username']??'');?><div class="forwarded-label">Переслано от <?php if($fwdUser!==''):?><a href="<?=e(user_public_url($fwdUser))?>"><?=e($m['forwarded_from_name']??'пользователя')?></a><?php else:?><?=e($m['forwarded_from_name']??'пользователя')?><?php endif;?><?php if(!empty($m['forwarded_from_created_at'])):?><time><?=e(date('d.m.Y H:i',strtotime((string)$m['forwarded_from_created_at'])))?></time><?php endif;?></div><?php endif;?>
  <?php if(($m['type']??'')==='post'&&!empty($m['shared_post_id'])):$shared=profile_post_share_data((int)$m['shared_post_id']);$sharedFull=$shared?profile_post_for_render((int)$m['shared_post_id']):null;?>
   <?php if($shared):$sharedImage=array_values(array_filter($shared['attachments']??[],fn($a)=>str_starts_with((string)($a['mime_type']??''),'image/')))[0]??null;?><button type="button" class="message-shared-post" data-shared-post-open="<?=(int)$shared['id']?>" aria-label="Открыть запись"><header><?=avatar_html(['id'=>$shared['author_id'],'display_name'=>$shared['author_name'],'avatar_path'=>$shared['avatar_path']??null],'avatar-xs')?><span><b><?=e($shared['author_name'])?></b><small>запись на стене</small></span></header><?php if(trim((string)$shared['body'])!==''):?><p><?=e(utf8_substr(trim(strip_tags((string)$shared['body'])),0,360))?></p><?php endif;?><?php if($sharedImage):?><img src="<?=e($sharedImage['url'])?>" alt="Фотография публикации" loading="lazy"><?php endif;?></button><?php if($sharedFull):?><template data-shared-post-template="<?=(int)$shared['id']?>"><?=\Kovcheg\View::partial('feed-post',['post'=>$sharedFull])?></template><?php endif;?><?php else:?><div class="message-body">Публикация недоступна.</div><?php endif;?>
   <?php if(trim($plainBody)!==''):?><div class="message-body attachment-caption"><?=safe_message_html($plainBody)?></div><?php endif;?>
  <?php elseif($m['type']==='sticker'&&str_starts_with((string)$m['sticker_code'],'sticker:')):$sid=(int)substr((string)$m['sticker_code'],8);?><img class="custom-sticker" src="<?=e(app_url('/sticker/'.$sid))?>" alt="Стикер">
  <?php elseif($m['type']==='sticker'):?><div class="message-body emoji-message"><?=e($m['sticker_code'])?></div>
  <?php elseif($m['type']==='file'&&!empty($m['attachment_id'])):?>
   <?php if(is_image_attachment($m)):$inlineUrl=app_url('/download/'.(int)$m['attachment_id'].'?inline=1&v='.(int)$m['id']);?><button type="button" class="image-attachment" data-lightbox-src="<?=e($inlineUrl)?>" data-lightbox-name="<?=e($m['original_name'])?>"><img loading="eager" decoding="async" src="<?=e($inlineUrl)?>" alt="<?=e($m['original_name'])?>"><span class="media-error-text">Фото не загрузилось. Нажмите, чтобы открыть оригинал.</span></button>
   <?php elseif(str_starts_with((string)$m['mime_type'],'audio/')):?><div class="voice-message" data-voice-message><button type="button" class="voice-message-play" data-voice-message-play aria-label="Воспроизвести">▶</button><div class="voice-message-main"><div class="voice-message-wave" data-voice-message-wave><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><input type="range" min="0" max="1000" value="0" data-voice-message-range aria-label="Позиция записи"><small><time data-voice-message-time>0:00</time><span>Голосовое сообщение</span></small></div><button type="button" class="voice-speed" data-voice-speed>1×</button><audio preload="metadata" data-global-audio data-track-title="<?=e($m['original_name']?:'Голосовое сообщение')?>" data-track-author="<?=e($m['display_name']??'')?>" src="<?=e(media_url((int)$m['attachment_id']))?>"></audio></div>
   <?php elseif(str_starts_with((string)$m['mime_type'],'video/')):?><div class="media-attachment"><video controls preload="metadata" src="<?=e(media_url((int)$m['attachment_id']))?>"></video><small><?=e($m['original_name'])?> · <?=e(format_bytes((int)$m['file_size']))?></small></div>
   <?php else:?><a class="file-card" href="<?=e(app_url('/download/'.$m['attachment_id']))?>"><span>📎</span><span><b><?=e($m['original_name'])?></b><small><?=e(format_bytes((int)$m['file_size']))?></small></span></a><?php endif;?>
   <?php if(trim($plainBody)!==''):?><div class="message-body attachment-caption"><?=safe_message_html($plainBody)?></div><?php endif;?>
  <?php else:?><?php if(trim($plainBody)!==''):?><div class="message-body"><?=safe_message_html($plainBody)?></div><?php endif;?><?php endif;?>
  <div class="message-action-shell" data-message-action-shell>
   <button type="button" class="message-more-button" data-message-menu-toggle aria-haspopup="menu" aria-expanded="false" aria-label="Действия с сообщением" title="Действия">•••</button>
   <div class="message-action-menu" data-message-action-menu role="menu" hidden>
    <?php if(!$threadMode):?><button type="button" data-reply role="menuitem"><span>↩</span>Ответить</button><?php endif;?>
    <?php if($showReactions):?><button type="button" data-reaction-menu role="menuitem"><span>♡</span>Реакция</button><?php endif;?>
    <?php if(empty($m['content_protection'])&&!$threadMode):?><button type="button" data-forward role="menuitem"><span>↗</span>Переслать</button><?php endif;?>
    <button type="button" data-message-copy role="menuitem"><span>⧉</span>Копировать</button>
    <?php if(($isMine&&can_do('can_edit_messages'))||!empty($moderation['edit'])):?><button type="button" data-edit role="menuitem"><span>✎</span>Изменить</button><?php endif;?>
    <?php if(message_can_delete_now($m,!empty($moderation['delete']))):?><button type="button" class="danger" data-delete role="menuitem"><span>⌫</span>Удалить</button><?php endif;?>
   </div>
  </div>
  <?php if($showReactions):?><div class="reaction-menu reaction-menu-modern" hidden><div class="reaction-primary"><?php foreach(['👍','❤️','🔥','😂','😮','😢','👏','🎉'] as $emoji):?><button type="button" data-message-react-modern="<?=e($emoji)?>"><?=e($emoji)?></button><?php endforeach;?><button type="button" data-reaction-more aria-label="Больше реакций">•••</button></div><div class="reaction-more-grid" hidden><?php foreach(['😁','🤣','😍','🥰','😘','🤩','🥳','🤔','🤯','😡','🤬','🙏','💪','👌','🤝','🙌','💯','⚡','⭐','🎯','✅','❌','👀','🤗'] as $emoji):?><button type="button" data-message-react-modern="<?=e($emoji)?>"><?=e($emoji)?></button><?php endforeach;?></div></div><div class="reactions"><?php foreach($reactions as $reaction):?><button type="button" class="<?=!empty($reaction['mine'])?'mine':''?>" data-react="<?=e($reaction['emoji'])?>"><?=e($reaction['emoji'])?> <span><?=e($reaction['count'])?></span></button><?php endforeach;?></div><?php endif;?>
  <?php if(!$threadMode&&!$postViewerMode&&($m['chat_type']??'')==='channel'&&!empty($m['comments_enabled'])):$postChat=['id'=>(int)$m['chat_id'],'username'=>(string)($m['chat_username']??'')];if($postChat['username']==='')$postChat['username']=(string)(\Kovcheg\DB::one('SELECT username FROM chats WHERE id=?',[$postChat['id']])['username']??'');?><a class="comments-link" href="<?=e(channel_post_public_url($postChat,(int)$m['id']))?>">💬 <span><?=((int)($m['comments_count']??0)>0)?((int)$m['comments_count'].' комментариев'):'Комментировать'?></span></a><?php endif;?>
  <?php if(!empty($m['edited_at'])):?><small class="edited">изменено</small><?php endif;?>
 </div>
</article>
