<?php
require_once BASE_PATH.'/app/profile-banner.php';
$viewer=\Kovcheg\Auth::check()?\Kovcheg\Auth::id():0;$isSelf=$viewer===(int)$profileUser['id'];$relationship=$relationship??[];$counts=$counts??profile_counts((int)$profileUser['id']);$peopleBlocks=$peopleBlocks??[];$stories=$stories??[];$avatarReactions=$avatarReactions??[];
$showLastSeen=$isSelf||\Kovcheg\Auth::isAdmin()||raw_user_setting((int)$profileUser['id'],'last_seen_visibility','colleagues')==='everyone'||(raw_user_setting((int)$profileUser['id'],'last_seen_visibility','colleagues')==='colleagues'&&$viewer&&are_colleagues($viewer,(int)$profileUser['id']));
?>
<main class="site-page-shell public-user-shell vk-site-shell <?=\Kovcheg\Auth::check()?'':'public-guest-shell'?>"><?php if(\Kovcheg\Auth::check()):?><?=\Kovcheg\View::partial('site-sidebar',['active'=>'profile'])?><?php endif;?>
 <section class="vk-profile-page public-vk-profile profile-page-090"><?php $publicBannerUrl=profile_banner_url((int)$profileUser['id']);?><?php if($publicBannerUrl!==''):?><div class="profile-public-banner" style="background-image:url('<?=e($publicBannerUrl)?>')"></div><?php endif;?><div class="vk-profile-grid vk-profile-grid-090 has-right">
  <aside class="vk-profile-left"><?=\Kovcheg\View::partial('profile-avatar-controls',compact('profileUser','stories','avatarReactions'))?>
   <?php if($isSelf):?><a class="btn btn-primary vk-wide-button" href="<?=e(app_url('/settings/general'))?>">Редактировать профиль</a>
   <?php elseif($viewer):?><?php if(!empty($relationship['blocked_by_me'])):?><button class="btn btn-primary vk-wide-button" type="button" data-profile-unblock="<?=(int)$profileUser['id']?>">Разблокировать</button><?php else:?><form method="post" action="<?=e(app_url('/chat/direct'))?>"><?=csrf_field()?><input type="hidden" name="user_id" value="<?=(int)$profileUser['id']?>"><button class="btn btn-primary vk-wide-button">Написать сообщение</button></form><div class="profile-action-stack" data-profile-actions data-user-id="<?=(int)$profileUser['id']?>"><?php if(!empty($relationship['colleagues'])):?><button class="btn vk-wide-button" type="button" data-colleague-action="remove">Убрать из коллег</button><?php elseif(!empty($relationship['request_outgoing'])&&($relationship['request_status']??'')==='pending'):?><button class="btn vk-wide-button" disabled>Заявка отправлена</button><?php elseif(!empty($relationship['following'])):?><button class="btn vk-wide-button" type="button" data-follow-action="unfollow">Отписаться</button><button class="btn vk-wide-button" type="button" data-colleague-action="request">Добавить в коллеги</button><?php else:?><button class="btn vk-wide-button" type="button" data-colleague-action="request">Добавить в коллеги</button><?php endif;?></div>
   <button class="btn vk-wide-button danger" type="button" data-profile-block="<?=(int)$profileUser['id']?>">Добавить в чёрный список</button><?php endif;?>
   <?php else:?><a class="btn btn-primary vk-wide-button" href="<?=e(app_url('/login'))?>">Войти</a><?php endif;?>
   <?php if($canView):?><?=\Kovcheg\View::partial('profile-people-blocks',['profileUser'=>$profileUser,'peopleBlocks'=>$peopleBlocks])?><?php endif;?>
  </aside>
  <div class="vk-profile-main"><article class="vk-profile-info-card profile-info-090"><header><div><h1><?=e($profileUser['display_name'])?><?=verified_badge($profileUser,'verified-badge verified-large')?></h1><a href="<?=e(user_public_url((string)$profileUser['username']))?>">@<?=e($profileUser['username'])?></a></div><?php if($showLastSeen):?><span class="profile-online" data-presence-user="<?=(int)$profileUser['id']?>"><?=online($profileUser['last_seen_at']??null)?'в сети':'был(а) '.e(human_time($profileUser['last_seen_at']??null))?></span><?php endif;?></header>
   <?php if($canView):?><?php if(!empty($profileUser['status_text'])):?><div class="profile-status-display"><?=e($profileUser['status_text'])?></div><?php endif;?><?php if(!empty($profileUser['bio'])):?><div class="vk-bio"><?=nl2br(e($profileUser['bio']))?></div><?php endif;?><?php else:?><div class="private-profile-note"><b>Страница ограничена</b><span>Владелец профиля ограничил просмотр.</span></div><?php endif;?></article>
   <?php if($canView):?><article class="vk-profile-stats"><span><b><?=e($counts['colleagues'])?></b><small>коллег</small></span><span><b><?=e($counts['followers'])?></b><small>подписчиков</small></span><span><b><?=e($counts['following'])?></b><small>подписок</small></span></article><?=\Kovcheg\View::partial('profile-wall',['profileUser'=>$profileUser,'wallPosts'=>$wallPosts??[],'canPostWall'=>$canPostWall??false])?><?php endif;?>
  </div>
  <aside class="vk-profile-right"><?php if($canView):?><?=\Kovcheg\View::partial('weather-widget',['weatherUserId'=>(int)$profileUser['id']])?><?php endif;?><article class="vk-right-card"><header><b>Дополнительные блоки</b></header><p>Здесь появятся блоки модулей и групп.</p></article></aside>
 </div></section>
</main>
<?=\Kovcheg\View::partial('profile-avatar-modals',['profileUser'=>$profileUser])?>
