<?php
$current=$forecast['current']??[];$hourly=$forecast['hourly']??[];$daily=$forecast['daily']??[];$place=$forecast['place']??['name'=>$city,'admin1'=>''];$longDaily=$longForecast['daily']??[];
$weatherJson=json_encode(['place'=>$place,'current'=>$current,'hourly'=>$hourly,'daily'=>$daily,'long'=>$longDaily,'radar'=>$radar],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);
$ruDays=['Sun'=>'вс','Mon'=>'пн','Tue'=>'вт','Wed'=>'ср','Thu'=>'чт','Fri'=>'пт','Sat'=>'сб'];
?>
<main class="site-page-shell weather-shell-170"><?php echo \Kovcheg\View::partial('site-sidebar',['active'=>'']);?>
 <section class="weather-page-170" data-weather-page>
  <header class="weather-hero-170"><div><a href="<?=e(app_url('/feed'))?>">← Назад</a><h1><?=e(implode(', ',array_filter([$place['name']??$city,$place['admin1']??''])))?></h1><p><?=e(weather_code_text((int)($current['weather_code']??0)))?> · ощущается как <?=round((float)($current['apparent_temperature']??0))?>°</p></div><div class="weather-hero-temp"><span><?=weather_code_icon((int)($current['weather_code']??0))?></span><b><?=round((float)($current['temperature_2m']??0))?>°</b></div></header>
  <?php if(!empty($forecast['error'])):?><div class="weather-page-error"><?=e($forecast['error'])?></div><?php endif;?>
  <nav class="weather-tabs-170"><button class="active" type="button" data-weather-tab="radar">Осадки</button><button type="button" data-weather-tab="ten">10 дней</button><button type="button" data-weather-tab="month">30 дней</button></nav>
  <section class="weather-panel-170 active" data-weather-panel="radar">
   <article class="weather-radar-card"><header><div><h2>Где сейчас идёт дождь и снег</h2><p>Радар осадков: зелёный — слабые, жёлтый — умеренные, красный — сильные осадки</p></div><time data-radar-time>—</time></header><div id="weather-radar-map" data-lat="<?=e((string)($place['latitude']??0))?>" data-lon="<?=e((string)($place['longitude']??0))?>"></div><div class="weather-radar-legend"><span><i class="rain-weak"></i>Слабые</span><span><i class="rain-medium"></i>Умеренные</span><span><i class="rain-heavy"></i>Сильные</span><span><i class="rain-snow"></i>Снег</span></div><footer><button type="button" data-radar-prev>←</button><input type="range" min="0" max="0" value="0" data-radar-range><button type="button" data-radar-next>→</button><button type="button" data-radar-play>▶</button></footer></article>
   <article class="weather-rain-timeline"><header><div><h2>Дождь сегодня и завтра</h2><p>Почасовая вероятность и количество осадков для выбранного города</p></div></header><div class="weather-day-switch"><button class="active" data-rain-day="0" type="button">Сегодня</button><button data-rain-day="1" type="button">Завтра</button></div><div class="weather-hour-strip" data-rain-hours></div><div class="weather-rain-summary" data-rain-summary></div></article>
  </section>
  <section class="weather-panel-170" data-weather-panel="ten" hidden><header class="weather-section-head"><h2>Прогноз на 10 дней</h2><p>Температура, вероятность и количество осадков</p></header><div class="weather-ten-grid"><?php foreach(array_slice($daily['time']??[],0,10) as $i=>$date):$dt=new DateTime($date);?><article><header><b><?=$i===0?'Сегодня':($i===1?'Завтра':e($ruDays[$dt->format('D')]??$dt->format('D'))) ?></b><small><?=$dt->format('d.m')?></small></header><span><?=weather_code_icon((int)($daily['weather_code'][$i]??0))?></span><div><strong><?=round((float)($daily['temperature_2m_max'][$i]??0))?>°</strong><em><?=round((float)($daily['temperature_2m_min'][$i]??0))?>°</em></div><p><?=e(weather_code_text((int)($daily['weather_code'][$i]??0)))?></p><footer><b>💧 <?=round((float)($daily['precipitation_probability_max'][$i]??0))?>%</b><small><?=number_format((float)($daily['precipitation_sum'][$i]??0),1,',',' ')?> мм</small></footer></article><?php endforeach;?></div></section>
  <section class="weather-panel-170" data-weather-panel="month" hidden><header class="weather-section-head"><h2>Тенденция на 30 дней</h2><p>Долгосрочный ансамблевый прогноз. Чем дальше дата, тем выше неопределённость.</p></header><?php if(!empty($longDaily['time'])):?><div class="weather-month-grid"><?php foreach(array_slice($longDaily['time'],0,30) as $i=>$date):$dt=new DateTime($date);?><article><time><?=$dt->format('d.m')?></time><span><?=weather_long_icon((float)($longDaily['temperature_2m_max'][$i]??0),(float)($longDaily['precipitation_sum'][$i]??0))?></span><b><?=round((float)($longDaily['temperature_2m_max'][$i]??0))?>°</b><small><?=round((float)($longDaily['temperature_2m_min'][$i]??0))?>°</small><em><?=number_format((float)($longDaily['precipitation_sum'][$i]??0),1,',',' ')?> мм</em></article><?php endforeach;?></div><?php else:?><div class="weather-page-error">Долгосрочный прогноз временно недоступен. Краткий прогноз продолжает работать.</div><?php endif;?></section>
  <footer class="weather-source-note">Прогнозные данные обновляются автоматически. Радар показывает фактические области дождя и снега по последним доступным наблюдениям; время дождя сегодня и завтра рассчитывается по почасовому прогнозу.</footer>
 </section>
</main>
<script type="application/json" data-weather-state><?=$weatherJson?:'{}'?></script>
