<?php

declare(strict_types=1);

return <<<'SQL'
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(100) PRIMARY KEY, `value` LONGTEXT NULL, updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,username VARCHAR(80) NOT NULL UNIQUE,first_name VARCHAR(80) NULL,last_name VARCHAR(80) NULL,display_name VARCHAR(150) NOT NULL,avatar_path VARCHAR(255) NULL,bio TEXT NULL,status_text VARCHAR(190) NULL,birthday DATE NULL,password_hash VARCHAR(255) NOT NULL,role VARCHAR(30) NOT NULL DEFAULT 'user',is_verified TINYINT(1) NOT NULL DEFAULT 0,verification_label VARCHAR(80) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,approval_status VARCHAR(20) NOT NULL DEFAULT 'approved',approved_by BIGINT UNSIGNED NULL,approved_at DATETIME NULL,last_seen_at DATETIME NULL,created_at DATETIME NULL,updated_at DATETIME NULL,INDEX idx_users_last_seen(last_seen_at),INDEX idx_users_approval(approval_status,is_active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_settings (user_id BIGINT UNSIGNED NOT NULL,`key` VARCHAR(100) NOT NULL,`value` LONGTEXT NULL,updated_at DATETIME NULL,PRIMARY KEY(user_id,`key`),CONSTRAINT fk_user_settings_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_permissions (user_id BIGINT UNSIGNED PRIMARY KEY,can_send_messages TINYINT(1) NOT NULL DEFAULT 1,can_send_files TINYINT(1) NOT NULL DEFAULT 1,can_send_stickers TINYINT(1) NOT NULL DEFAULT 1,can_send_voice TINYINT(1) NOT NULL DEFAULT 1,can_create_channels TINYINT(1) NOT NULL DEFAULT 0,can_invite_members TINYINT(1) NOT NULL DEFAULT 1,can_edit_messages TINYINT(1) NOT NULL DEFAULT 1,can_delete_messages TINYINT(1) NOT NULL DEFAULT 1,updated_at DATETIME NULL,CONSTRAINT fk_user_permissions_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS roles (slug VARCHAR(40) PRIMARY KEY,name VARCHAR(100) NOT NULL,description VARCHAR(255) NULL,is_system TINYINT(1) NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 100,created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS role_permissions (role_slug VARCHAR(40) NOT NULL,permission_key VARCHAR(80) NOT NULL,is_allowed TINYINT(1) NOT NULL DEFAULT 0,updated_at DATETIME NULL,PRIMARY KEY(role_slug,permission_key),CONSTRAINT fk_role_permission_role FOREIGN KEY(role_slug) REFERENCES roles(slug) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO roles (slug,name,description,is_system,sort_order,created_at,updated_at) VALUES ('owner','Владелец','Полный доступ',1,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('admin','Администратор','Управление системой',1,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('editor','Редактор','Контент и коммуникации',1,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('user','Пользователь','Стандартный доступ',1,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('guest','Гость','Ограниченный доступ',1,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);




CREATE TABLE IF NOT EXISTS user_blocks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,blocker_id BIGINT UNSIGNED NOT NULL,blocked_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NULL,UNIQUE KEY uniq_user_block(blocker_id,blocked_id),INDEX idx_user_blocks_blocked(blocked_id,blocker_id),CONSTRAINT fk_user_blocks_blocker FOREIGN KEY(blocker_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_user_blocks_blocked FOREIGN KEY(blocked_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS avatar_comments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,profile_user_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,parent_id BIGINT UNSIGNED NULL,body TEXT NOT NULL,created_at DATETIME NULL,updated_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_avatar_comments_profile(profile_user_id,id),INDEX idx_avatar_comments_parent(parent_id,id),CONSTRAINT fk_avatar_comments_profile FOREIGN KEY(profile_user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_avatar_comments_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_avatar_comments_parent FOREIGN KEY(parent_id) REFERENCES avatar_comments(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS chats (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,type VARCHAR(20) NOT NULL,title VARCHAR(190) NULL,username VARCHAR(80) NULL UNIQUE,description TEXT NULL,avatar_path VARCHAR(255) NULL,visibility VARCHAR(20) NOT NULL DEFAULT 'private',join_policy VARCHAR(20) NOT NULL DEFAULT 'invite',comments_enabled TINYINT(1) NOT NULL DEFAULT 0,reactions_enabled TINYINT(1) NOT NULL DEFAULT 1,sign_messages TINYINT(1) NOT NULL DEFAULT 0,content_protection TINYINT(1) NOT NULL DEFAULT 0,slow_mode_seconds INT NOT NULL DEFAULT 0,owner_id BIGINT UNSIGNED NOT NULL,is_pinned TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NULL,updated_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_chats_updated(updated_at),INDEX idx_chats_type_visibility(type,visibility),CONSTRAINT fk_chats_owner FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS chat_members (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,chat_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'member',last_read_message_id BIGINT UNSIGNED NULL,cleared_before_message_id BIGINT UNSIGNED NULL,is_muted TINYINT(1) NOT NULL DEFAULT 0,is_pinned TINYINT(1) NOT NULL DEFAULT 0,is_archived TINYINT(1) NOT NULL DEFAULT 0,is_hidden TINYINT(1) NOT NULL DEFAULT 0,can_post TINYINT(1) NOT NULL DEFAULT 0,can_edit_posts TINYINT(1) NOT NULL DEFAULT 0,can_delete_posts TINYINT(1) NOT NULL DEFAULT 0,can_invite TINYINT(1) NOT NULL DEFAULT 0,can_manage_members TINYINT(1) NOT NULL DEFAULT 0,can_manage_settings TINYINT(1) NOT NULL DEFAULT 0,joined_at DATETIME NULL,UNIQUE KEY uniq_chat_user(chat_id,user_id),INDEX idx_member_user(user_id,is_hidden,is_archived,is_pinned),CONSTRAINT fk_cm_chat FOREIGN KEY(chat_id) REFERENCES chats(id) ON DELETE CASCADE,CONSTRAINT fk_cm_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,chat_id BIGINT UNSIGNED NOT NULL,sender_id BIGINT UNSIGNED NOT NULL,type VARCHAR(20) NOT NULL DEFAULT 'text',body LONGTEXT NULL,sticker_code VARCHAR(64) NULL,reply_to_id BIGINT UNSIGNED NULL,thread_root_id BIGINT UNSIGNED NULL,forwarded_from_id BIGINT UNSIGNED NULL,shared_post_id BIGINT UNSIGNED NULL,created_at DATETIME NULL,edited_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_messages_chat_id(chat_id,id),INDEX idx_messages_sender(sender_id),INDEX idx_messages_forwarded(forwarded_from_id),INDEX idx_messages_thread_root(thread_root_id,id),FULLTEXT KEY ft_messages_body(body),CONSTRAINT fk_msg_chat FOREIGN KEY(chat_id) REFERENCES chats(id) ON DELETE CASCADE,CONSTRAINT fk_msg_sender FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS chat_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,chat_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(40) NOT NULL,message_id BIGINT UNSIGNED NULL,actor_id BIGINT UNSIGNED NULL,payload_json LONGTEXT NULL,created_at DATETIME NULL,INDEX idx_chat_events_chat_id(chat_id,id),INDEX idx_chat_events_created(created_at),CONSTRAINT fk_chat_events_chat FOREIGN KEY(chat_id) REFERENCES chats(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS attachments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,message_id BIGINT UNSIGNED NOT NULL UNIQUE,original_name VARCHAR(255) NOT NULL,stored_path VARCHAR(255) NOT NULL,mime_type VARCHAR(150) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,created_at DATETIME NULL,CONSTRAINT fk_att_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS message_bookmarks (message_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NULL,PRIMARY KEY(message_id,user_id),INDEX idx_message_bookmarks_user(user_id,created_at),CONSTRAINT fk_message_bookmark_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE,CONSTRAINT fk_message_bookmark_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS message_reactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,message_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,emoji VARCHAR(32) NOT NULL,created_at DATETIME NULL,UNIQUE KEY uniq_reaction(message_id,user_id,emoji),CONSTRAINT fk_react_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE,CONSTRAINT fk_react_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS sticker_packs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,slug VARCHAR(100) NOT NULL UNIQUE,author VARCHAR(150) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,is_system TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS stickers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,pack_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,stored_path VARCHAR(255) NOT NULL,mime_type VARCHAR(100) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NULL,CONSTRAINT fk_sticker_pack FOREIGN KEY(pack_id) REFERENCES sticker_packs(id) ON DELETE CASCADE,INDEX idx_stickers_pack(pack_id,is_active,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS modules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL,version VARCHAR(30) NOT NULL,description TEXT NULL,enabled TINYINT(1) NOT NULL DEFAULT 0,installed_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS api_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,abilities TEXT NULL,last_used_at DATETIME NULL,revoked_at DATETIME NULL,created_at DATETIME NULL,CONSTRAINT fk_token_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS webhooks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,url VARCHAR(500) NOT NULL,secret_encrypted TEXT NOT NULL,events TEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS webhook_deliveries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,webhook_id BIGINT UNSIGNED NOT NULL,event VARCHAR(120) NOT NULL,payload_json LONGTEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',attempts INT NOT NULL DEFAULT 0,next_attempt_at DATETIME NULL,last_error TEXT NULL,created_at DATETIME NULL,delivered_at DATETIME NULL,INDEX idx_webhook_queue(status,next_attempt_at),CONSTRAINT fk_delivery_webhook FOREIGN KEY(webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS admin_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,type VARCHAR(50) NOT NULL DEFAULT 'info',title VARCHAR(190) NOT NULL,body TEXT NULL,url VARCHAR(500) NULL,actor_id BIGINT UNSIGNED NULL,created_at DATETIME NULL,INDEX idx_admin_notifications_created(created_at),CONSTRAINT fk_admin_notification_actor FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS admin_notification_reads (notification_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,read_at DATETIME NULL,PRIMARY KEY(notification_id,user_id),CONSTRAINT fk_admin_read_notification FOREIGN KEY(notification_id) REFERENCES admin_notifications(id) ON DELETE CASCADE,CONSTRAINT fk_admin_read_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS channel_invite_links (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,chat_id BIGINT UNSIGNED NOT NULL,token CHAR(48) NOT NULL UNIQUE,label VARCHAR(120) NULL,expires_at DATETIME NULL,max_uses INT NULL,uses_count INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_by BIGINT UNSIGNED NOT NULL,created_at DATETIME NULL,INDEX idx_channel_invites(chat_id,is_active),CONSTRAINT fk_channel_invite_chat FOREIGN KEY(chat_id) REFERENCES chats(id) ON DELETE CASCADE,CONSTRAINT fk_channel_invite_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS channel_join_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,chat_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',created_at DATETIME NULL,reviewed_at DATETIME NULL,reviewed_by BIGINT UNSIGNED NULL,UNIQUE KEY uniq_channel_join_request(chat_id,user_id),INDEX idx_join_requests_status(chat_id,status),CONSTRAINT fk_join_request_chat FOREIGN KEY(chat_id) REFERENCES chats(id) ON DELETE CASCADE,CONSTRAINT fk_join_request_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_join_request_reviewed FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS push_subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,endpoint_hash CHAR(64) NOT NULL UNIQUE,endpoint TEXT NOT NULL,p256dh VARCHAR(255) NULL,auth_token VARCHAR(255) NULL,user_agent VARCHAR(255) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NULL,updated_at DATETIME NULL,CONSTRAINT fk_push_subscription_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS push_deliveries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,title VARCHAR(190) NOT NULL,body TEXT NULL,url VARCHAR(500) NULL,icon VARCHAR(500) NULL,tag VARCHAR(190) NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',attempts INT NOT NULL DEFAULT 0,next_attempt_at DATETIME NULL,last_error TEXT NULL,created_at DATETIME NULL,delivered_at DATETIME NULL,consumed_at DATETIME NULL,INDEX idx_push_queue(status,next_attempt_at),INDEX idx_push_user(user_id,consumed_at),CONSTRAINT fk_push_delivery_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_follows (follower_id BIGINT UNSIGNED NOT NULL,followed_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NULL,PRIMARY KEY(follower_id,followed_id),INDEX idx_followed_user(followed_id,created_at),CONSTRAINT fk_follow_follower FOREIGN KEY(follower_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_follow_followed FOREIGN KEY(followed_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS colleague_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,requester_id BIGINT UNSIGNED NOT NULL,recipient_id BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',created_at DATETIME NULL,updated_at DATETIME NULL,responded_at DATETIME NULL,UNIQUE KEY uniq_colleague_direction(requester_id,recipient_id),INDEX idx_colleague_recipient(recipient_id,status),INDEX idx_colleague_requester(requester_id,status),CONSTRAINT fk_colleague_requester FOREIGN KEY(requester_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_colleague_recipient FOREIGN KEY(recipient_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type VARCHAR(40) NOT NULL DEFAULT 'info',title VARCHAR(190) NOT NULL,body TEXT NULL,url VARCHAR(500) NULL,icon VARCHAR(500) NULL,tag VARCHAR(190) NULL,is_read TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NULL,read_at DATETIME NULL,INDEX idx_user_notifications(user_id,is_read,id),CONSTRAINT fk_user_notification_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS message_notification_queue (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,message_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,due_at DATETIME NOT NULL,created_at DATETIME NULL,delivered_at DATETIME NULL,cancelled_at DATETIME NULL,UNIQUE KEY uniq_message_user(message_id,user_id),INDEX idx_message_notification_due(delivered_at,cancelled_at,due_at),CONSTRAINT fk_message_notification_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE,CONSTRAINT fk_message_notification_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_avatar_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,stored_path VARCHAR(255) NOT NULL,mime_type VARCHAR(100) NOT NULL,file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,is_current TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NULL,INDEX idx_avatar_history_user(user_id,id),CONSTRAINT fk_avatar_history_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS profile_posts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,author_id BIGINT UNSIGNED NOT NULL,body TEXT NOT NULL,visibility VARCHAR(20) NOT NULL DEFAULT 'everyone',status VARCHAR(20) NOT NULL DEFAULT 'published',publish_at DATETIME NULL,repost_post_id BIGINT UNSIGNED NULL,created_at DATETIME NULL,updated_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_profile_posts(user_id,id),INDEX idx_profile_posts_publish(status,publish_at,id),INDEX idx_profile_posts_author_status(author_id,status,id),CONSTRAINT fk_profile_post_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_profile_post_author FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS profile_post_likes (post_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NULL,PRIMARY KEY(post_id,user_id),CONSTRAINT fk_profile_like_post FOREIGN KEY(post_id) REFERENCES profile_posts(id) ON DELETE CASCADE,CONSTRAINT fk_profile_like_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS profile_post_reactions (post_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,emoji VARCHAR(32) NOT NULL,created_at DATETIME NULL,PRIMARY KEY(post_id,user_id),INDEX idx_profile_post_reactions(post_id,emoji),CONSTRAINT fk_profile_post_reaction_post FOREIGN KEY(post_id) REFERENCES profile_posts(id) ON DELETE CASCADE,CONSTRAINT fk_profile_post_reaction_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS avatar_reactions (avatar_history_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,emoji VARCHAR(32) NOT NULL,created_at DATETIME NULL,PRIMARY KEY(avatar_history_id,user_id),INDEX idx_avatar_reactions_emoji(avatar_history_id,emoji),CONSTRAINT fk_avatar_reaction_photo FOREIGN KEY(avatar_history_id) REFERENCES user_avatar_history(id) ON DELETE CASCADE,CONSTRAINT fk_avatar_reaction_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_stories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,stored_path VARCHAR(255) NOT NULL,mime_type VARCHAR(100) NOT NULL,file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,caption VARCHAR(500) NULL,expires_at DATETIME NOT NULL,created_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_story_active(user_id,expires_at,deleted_at),CONSTRAINT fk_story_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS story_views (story_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,viewed_at DATETIME NULL,PRIMARY KEY(story_id,user_id),CONSTRAINT fk_story_view_story FOREIGN KEY(story_id) REFERENCES user_stories(id) ON DELETE CASCADE,CONSTRAINT fk_story_view_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS profile_post_attachments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id BIGINT UNSIGNED NOT NULL,stored_path VARCHAR(255) NOT NULL,mime_type VARCHAR(100) NOT NULL,file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 0,original_name VARCHAR(255) NULL,created_at DATETIME NULL,INDEX idx_profile_post_attachment(post_id,sort_order,id),CONSTRAINT fk_profile_post_attachment_post FOREIGN KEY(post_id) REFERENCES profile_posts(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS profile_post_comments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,parent_id BIGINT UNSIGNED NULL,body TEXT NOT NULL,created_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_profile_post_comments(post_id,id),INDEX idx_profile_post_comment_parent(parent_id),CONSTRAINT fk_profile_post_comment_post FOREIGN KEY(post_id) REFERENCES profile_posts(id) ON DELETE CASCADE,CONSTRAINT fk_profile_post_comment_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,entity_type VARCHAR(80) NULL,entity_id BIGINT UNSIGNED NULL,ip VARCHAR(64) NULL,meta_json LONGTEXT NULL,created_at DATETIME NULL,INDEX idx_audit_created(created_at),INDEX idx_audit_action(action)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comment_reactions (
 context_type VARCHAR(20) NOT NULL,
 comment_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 emoji VARCHAR(32) NOT NULL,
 created_at DATETIME NULL,
 PRIMARY KEY(context_type,comment_id,user_id),
 INDEX idx_comment_reactions_lookup(context_type,comment_id,emoji),
 CONSTRAINT fk_comment_reactions_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_rate_limits (
 rate_key CHAR(64) PRIMARY KEY,
 attempts INT NOT NULL DEFAULT 0,
 window_started_at DATETIME NOT NULL,
 blocked_until DATETIME NULL,
 updated_at DATETIME NULL,
 INDEX idx_auth_rate_blocked(blocked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS archive_comment_tracks (
  comment_id BIGINT UNSIGNED NOT NULL,
  file_id BIGINT UNSIGNED NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NULL,
  PRIMARY KEY(comment_id,file_id),
  INDEX idx_archive_comment_tracks_file(file_id,comment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS archive_content_moderation (
  file_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  blocked_until DATETIME NULL,
  reason VARCHAR(500) NULL,
  moderated_by BIGINT UNSIGNED NULL,
  moderated_at DATETIME NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  INDEX idx_archive_moderation_status(status,blocked_until),
  INDEX idx_archive_moderation_admin(moderated_by,moderated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SQL;
